# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoSource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTbl',
            fields=[
                ('board_id', models.AutoField(db_column='BOARD_ID', primary_key=True, serialize=False)),
                ('board_name', models.CharField(blank=True, db_column='BOARD_NAME', max_length=100, null=True)),
                ('group_id', models.IntegerField(blank=True, db_column='GROUP_ID', null=True)),
                ('memebership_id', models.IntegerField(blank=True, db_column='MEMEBERSHIP_ID', null=True)),
                ('created_dttm', models.DateTimeField(blank=True, db_column='CREATED_DTTM', null=True)),
            ],
            options={
                'db_table': 'BOARD_TBL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTbl',
            fields=[
                ('group_id', models.AutoField(db_column='GROUP_ID', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_column='USER_ID', null=True)),
                ('group_name', models.CharField(blank=True, db_column='GROUP_NAME', max_length=45, null=True)),
                ('lastupd_dttm', models.DateTimeField(blank=True, db_column='LASTUPD_DTTM', null=True)),
                ('created_dttm', models.DateTimeField(blank=True, db_column='CREATED_DTTM', null=True)),
            ],
            options={
                'db_table': 'GROUP_TBL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipTbl',
            fields=[
                ('seq_id', models.AutoField(db_column='SEQ_ID', primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(blank=True, db_column='GROUP_ID', null=True)),
                ('user_id', models.IntegerField(blank=True, db_column='USER_ID', null=True)),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=45, null=True)),
                ('lastupd_dttm', models.DateTimeField(blank=True, db_column='LASTUPD_DTTM', null=True)),
            ],
            options={
                'db_table': 'MEMBERSHIP_TBL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PanelTbl',
            fields=[
                ('panel_id', models.AutoField(db_column='PANEL_ID', primary_key=True, serialize=False)),
                ('panel_name', models.CharField(blank=True, db_column='PANEL_NAME', max_length=45, null=True)),
                ('board_id', models.IntegerField(blank=True, db_column='BOARD_ID', null=True)),
                ('create_dttm', models.DateTimeField(blank=True, db_column='CREATE_DTTM', null=True)),
                ('lastupd_dttm', models.DateTimeField(blank=True, db_column='LASTUPD_DTTM', null=True)),
            ],
            options={
                'db_table': 'PANEL_TBL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReminderTbl',
            fields=[
                ('seq_id', models.AutoField(db_column='SEQ_ID', primary_key=True, serialize=False)),
                ('task_id', models.IntegerField(blank=True, db_column='TASK_ID', null=True)),
                ('user_id', models.IntegerField(blank=True, db_column='USER_ID', null=True)),
                ('reminder_type', models.CharField(blank=True, db_column='REMINDER_TYPE', max_length=1, null=True)),
                ('user_emailid', models.CharField(blank=True, db_column='USER_EMAILID', max_length=45, null=True)),
                ('reminder_time', models.DateTimeField(blank=True, db_column='REMINDER_TIME', null=True)),
                ('reminder_timezone', models.CharField(blank=True, db_column='REMINDER_TIMEZONE', max_length=250, null=True)),
                ('lastupd_dttm', models.DateTimeField(blank=True, db_column='LASTUPD_DTTM', null=True)),
            ],
            options={
                'db_table': 'REMINDER_TBL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TasksTbl',
            fields=[
                ('task_id', models.AutoField(db_column='TASK_ID', primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, db_column='TASK_NAME', max_length=250, null=True)),
                ('panel_id', models.IntegerField(blank=True, db_column='PANEL_ID', null=True)),
                ('board_id', models.IntegerField(blank=True, db_column='BOARD_ID', null=True)),
                ('lastupd_dttm', models.DateTimeField(blank=True, db_column='LASTUPD_DTTM', null=True)),
            ],
            options={
                'db_table': 'TASKS_TBL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfileTbl',
            fields=[
                ('user_id', models.AutoField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=45, null=True)),
                ('emailid', models.CharField(blank=True, db_column='EMAILID', max_length=45, null=True)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', max_length=100, null=True)),
                ('avatar_url', models.ImageField(upload_to='/profile')),
                ('contact', models.CharField(blank=True, db_column='CONTACT', max_length=45, null=True)),
                ('access_token', models.CharField(blank=True, db_column='ACCESS_TOKEN', max_length=45, null=True)),
                ('lastupd_dttm', models.DateTimeField(blank=True, db_column='LASTUPD_DTTM', null=True)),
                ('created_dttm', models.DateTimeField(blank=True, db_column='CREATED_DTTM', null=True)),
            ],
            options={
                'db_table': 'USER_PROFILE_TBL',
                'managed': False,
            },
        ),
    ]
